<?php

namespace Database\Seeders;

use App\Models\Provinsi;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class provinsiSeeder extends Seeder
{
     public function run(): void
    {
        $data = [
            ['provinsi_indonesia' => 'Aceh',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],
            ['provinsi_indonesia' => 'Bali',
            'risk_score' => 3,
            'eqr_priority' => 'Medium',
        ],
            ['provinsi_indonesia' => 'Banten',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],
            ['provinsi_indonesia' => 'Bengkulu',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],
            ['provinsi_indonesia' => 'DI Yogyakarta',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],
            ['provinsi_indonesia' => 'DKI Jakarta',
            'risk_score' => 4,
            'eqr_priority' => 'High',
        ],
            ['provinsi_indonesia' => 'Gorontalo',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],
            ['provinsi_indonesia' => 'Jambi',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],
            ['provinsi_indonesia' => 'Jawa Barat',
            'risk_score' => 3,
            'eqr_priority' => 'Medium',
        ],
            ['provinsi_indonesia' => 'Jawa Tengah',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],
            ['provinsi_indonesia' => 'Jawa Timur',
            'risk_score' => 4,
            'eqr_priority' => 'High',
        ],
            ['provinsi_indonesia' => 'Kalimantan Barat',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],
            ['provinsi_indonesia' => 'Kalimantan Selatan',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],
            ['provinsi_indonesia' => 'Kalimantan Tengah',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],
            ['provinsi_indonesia' => 'Kalimantan Timur',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],
            ['provinsi_indonesia' => 'Kalimantan Utara',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],
            ['provinsi_indonesia' => 'Kepulauan Bangka Belitung',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],
            ['provinsi_indonesia' => 'Kepulauan Riau',
            'risk_score' => 3,
            'eqr_priority' => 'Medium',
        ],
            ['provinsi_indonesia' => 'Bandar Lampung',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],
            ['provinsi_indonesia' => 'Maluku',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],
            ['provinsi_indonesia' => 'Maluku Utara',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],
            ['provinsi_indonesia' => 'Nusa Tenggara Barat (NTB)',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],
            ['provinsi_indonesia' => 'Nusa Tenggara Timur (NTT)',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],
            ['provinsi_indonesia' => 'Papua',
            'risk_score' => 3,
            'eqr_priority' => 'Medium',
        ],
            ['provinsi_indonesia' => 'Papua Barat',
            'risk_score' => 3,
            'eqr_priority' => 'Medium',
        ],
            ['provinsi_indonesia' => 'Papua Barat Daya',
            'risk_score' => 3,
            'eqr_priority' => 'Medium',
        ],
            ['provinsi_indonesia' => 'Papua Pegunungan',
            'risk_score' => 3,
            'eqr_priority' => 'Medium',
        ],
            ['provinsi_indonesia' => 'Papua Selatan',
            'risk_score' => 3,
            'eqr_priority' => 'Medium',
        ],
            ['provinsi_indonesia' => 'Papua Tengah',
            'risk_score' => 3,
            'eqr_priority' => 'Medium',
        ],
           
            ['provinsi_indonesia' => 'Riau',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],
            ['provinsi_indonesia' => 'Sulawesi Barat',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],
            ['provinsi_indonesia' => 'Sulawesi Selatan',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],
            ['provinsi_indonesia' => 'Sulawesi Tengah',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],
            ['provinsi_indonesia' => 'Sulawesi Tenggara',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],
            ['provinsi_indonesia' => 'Sulawesi Utara',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],
            ['provinsi_indonesia' => 'Sumatera Barat',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],
            ['provinsi_indonesia' => 'Sumatera Selatan',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],
            ['provinsi_indonesia' => 'Sumatera Utara',
            'risk_score' => 4,
            'eqr_priority' => 'High',
        ],
            ['provinsi_indonesia' => 'Lainnya.',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],

          ['provinsi_indonesia' => 'Tax Heaven Country.',
            'risk_score' => 4,
            'eqr_priority' => 'High',
        ],

          ['provinsi_indonesia' => 'Tiongkok.',
            'risk_score' => 4,
            'eqr_priority' => 'High',
        ],

          ['provinsi_indonesia' => 'Singapura.',
            'risk_score' => 3,
            'eqr_priority' => 'Medium',
        ],
          ['provinsi_indonesia' => 'Provinsi Negara Lainnya.',
            'risk_score' => 2,
            'eqr_priority' => 'Low',
        ],



        ];

        foreach ($data as $item) {
            Provinsi::create($item);
        }
    }
}
